FileVersion: 1
Price:

  #创建地标的价格
  create: 300
  
  #添加别名的价格
  alias: 10
  
  #添加欢迎信息的价格
  welcome: 20
  
  #改变地标位置的价格
  relocation: 300

Limitation:

  #每种玩家可创建的地标的个数
  #Default默认: 无需权限
  #Admin管理员：OP或拥有wtp.admin权限
  #-1为无限制
  create: 
    default: 2
    admin: -1
  #其他组，可以自定义: WTP.create.VIP1, WTP.create.builder, 以此类推
    VIP1: 5
    VIP2: 8
    VIP3: 10
    builder: 20
